-- THIS FILE IS AUTO_GENERATED. DO NOT EDIT. ALL CHANGES WILL BE LOST.
-- LAST UPDATE FROM https://classic.wowhead.com AT 2020-07-11 04:19:16.640055 UTC

local L = GatherSage2.L
local module = GatherSage2:NewModule(L["Mining"])

local data = {
    [L["Copper Vein"]] = {
        {"1", "25", "50", "100"},
        L["Chance of"],
        {L["Copper Ore"], "1"},
        {L["Rough Stone"], "1"},
        {L["Malachite"], "2"},
        {L["Shadowgem"], "2"},
        {L["Tigerseye"], "2"},
    },
    [L["Tin Vein"]] = {
        {"65", "90", "115", "165"},
        L["Chance of"],
        {L["Coarse Stone"], "1"},
        {L["Tin Ore"], "1"},
        {L["Jade"], "2"},
        {L["Lesser Moonstone"], "2"},
        {L["Moss Agate"], "2"},
        {L["Shadowgem"], "2"},
    },
    [L["Silver Vein"]] = {
        {"75", "100", "125", "175"},
        L["Chance of"],
        {L["Lesser Moonstone"], "2"},
        {L["Moss Agate"], "2"},
        {L["Shadowgem"], "2"},
        {L["Silver Ore"], "2"},
    },
    [L["Iron Deposit"]] = {
        {"125", "150", "175", "225"},
        L["Chance of"],
        {L["Heavy Stone"], "1"},
        {L["Iron Ore"], "1"},
        {L["Aquamarine"], "2"},
        {L["Citrine"], "2"},
        {L["Jade"], "2"},
        {L["Lesser Moonstone"], "2"},
    },
    [L["Gold Vein"]] = {
        {"155", "180", "205", "255"},
        L["Chance of"],
        {L["Citrine"], "2"},
        {L["Gold Ore"], "2"},
        {L["Jade"], "2"},
        {L["Lesser Moonstone"], "2"},
    },
    [L["Mithril Deposit"]] = {
        {"175", "200", "225", "275"},
        L["Chance of"],
        {L["Black Vitriol"], "1"},
        {L["Mithril Ore"], "1"},
        {L["Solid Stone"], "1"},
        {L["Aquamarine"], "2"},
        {L["Citrine"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Ooze Covered Mithril Deposit"]] = {
        {"175", "200", "225", "275"},
        L["Chance of"],
        {L["Black Vitriol"], "1"},
        {L["Mithril Ore"], "1"},
        {L["Solid Stone"], "1"},
        {L["Aquamarine"], "2"},
        {L["Citrine"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Truesilver Deposit"]] = {
        {"230", "255", "280", "330"},
        L["Chance of"],
        {L["Aquamarine"], "2"},
        {L["Citrine"], "2"},
        {L["Star Ruby"], "2"},
        {L["Truesilver Ore"], "2"},
    },
    [L["Ooze Covered Truesilver Deposit"]] = {
        {"230", "255", "280", "330"},
        L["Chance of"],
        {L["Aquamarine"], "2"},
        {L["Citrine"], "2"},
        {L["Star Ruby"], "2"},
        {L["Truesilver Ore"], "2"},
    },
    [L["Dark Iron Deposit"]] = {
        {"230", "255", "280", "330"},
        L["Chance of"],
        {L["Black Vitriol"], "1"},
        {L["Dark Iron Ore"], "1"},
        {L["Black Diamond"], "2"},
        {L["Blood of the Mountain"], "2"},
    },
    [L["Small Thorium Vein"]] = {
        {"245", "270", "295", "345"},
        L["Chance of"],
        {L["Black Vitriol"], "1"},
        {L["Dense Stone"], "1"},
        {L["Thorium Ore"], "1"},
        {L["Blue Sapphire"], "2"},
        {L["Large Opal"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Ooze Covered Thorium Vein"]] = {
        {"245", "270", "295", "345"},
        L["Chance of"],
        {L["Black Vitriol"], "1"},
        {L["Dense Stone"], "1"},
        {L["Thorium Ore"], "1"},
        {L["Blue Sapphire"], "2"},
        {L["Large Opal"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Rich Thorium Vein"]] = {
        {"275", "290", "300", "350"},
        L["Chance of"],
        {L["Dense Stone"], "1"},
        {L["Thorium Ore"], "1"},
        {L["Arcane Crystal"], "2"},
        {L["Azerothian Diamond"], "2"},
        {L["Blue Sapphire"], "2"},
        {L["Huge Emerald"], "2"},
        {L["Large Opal"], "2"},
        {L["Souldarite"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Ooze Covered Rich Thorium Vein"]] = {
        {"275", "290", "300", "350"},
        L["Chance of"],
        {L["Dense Stone"], "1"},
        {L["Thorium Ore"], "1"},
        {L["Arcane Crystal"], "2"},
        {L["Azerothian Diamond"], "2"},
        {L["Blue Sapphire"], "2"},
        {L["Huge Emerald"], "2"},
        {L["Large Opal"], "2"},
        {L["Souldarite"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Hakkari Thorium Vein"]] = {
        {"275", "290", "300", "350"},
        L["Chance of"],
        {L["Dense Stone"], "1"},
        {L["Thorium Ore"], "1"},
        {L["Arcane Crystal"], "2"},
        {L["Azerothian Diamond"], "2"},
        {L["Blue Sapphire"], "2"},
        {L["Huge Emerald"], "2"},
        {L["Large Opal"], "2"},
        {L["Souldarite"], "2"},
        {L["Star Ruby"], "2"},
    },
    [L["Small Obsidian Chunk"]] = {
        {"305", "330", "355", "405"},
        L["Chance of"],
        {L["Large Obsidian Shard"], "1"},
        {L["Small Obsidian Shard"], "1"},
        {L["Arcane Crystal"], "2"},
        {L["Azerothian Diamond"], "2"},
        {L["Huge Emerald"], "2"},
    },
    [L["Large Obsidian Chunk"]] = {
        {"305", "330", "355", "405"},
        L["Chance of"],
        {L["Large Obsidian Shard"], "1"},
        {L["Small Obsidian Shard"], "1"},
        {L["Arcane Crystal"], "2"},
        {L["Azerothian Diamond"], "2"},
        {L["Huge Emerald"], "2"},
    }
}

module:SetProperty("data", data)
